dependents:
  - "openproblems/task_*" # include
  - "!openproblems/task_template" # exclude

additional:
  - "task_*" # include
  - "!task_template"

files:
  # Include
  - ".gitignore"

  # Exclude
  - "!README.md"
  - "!CHANGELOG.md"
  - "!_viash.yaml"
  - "!src/*/*/*"

  # Template sync action
  - "!.github/workflows/template-sync.yaml"
  - "!.github/template-sync-config.yaml"
