dependents:
  - "openproblems/task_*" # include
  - "!openproblems/task_template" # exclude

additional:
  - "task_*" # include
  - "!task_template"

files:
  # Include
  - ".gitignore"

  # Exclude
  - "!README.md"
  - "!CHANGELOG.md"
  - "!_viash.yaml"
  - "!src/api/*"
  - "!src/control_methods/*/*"
  - "!src/data_processors/*/*"
  - "!src/methods/*/*"
  - "!src/metrics/*/*"
  - "!src/workflows/*/*"

  # Template sync action
  - "!.github/workflows/template-sync.yaml"
  - "!.github/template-sync-config.yaml"
