dependents:
  - "openproblems/task_*" # include
  - "!openproblems/task_template" # exclude

additional:
  - "task_*" # include
  - "!task_template"

files:
  - ".gitignore" # include

  # Exclude the template sync action
  - "!.github/workflows/template-sync.yaml"
  - "!.github/template-sync-config.yaml"
